### PR TITLE
[DROOLS-5780] descope ecj

### PR DESCRIPTION
**Pull request by mariofusco**

### CODE REVIEW

**Comment by mariofusco** [comment]
jenkins execute fdb

**Review by lucamolteni — APPROVED** [review]

**Comment by mariofusco** [comment]
jenkins execute fdb

File: drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/NativeJavaCompiler.java [hunk 1]
```diff
@@ -347,12 +357,52 @@ public boolean hasLocation(Location location) {
...
+            }
+            return indexedClasses;
+        }
+
+        private void indexClassesByPackage(Map<String, Set<String>> indexedClasses, ClassLoader classLoader) {
+            if (classLoader instanceof ProjectClassLoader || classLoader == NativeJavaCompiler.class.getClassLoader()) {
+                return;
+            }
+            try {
+                Field classesField = ClassLoader.class.getDeclaredField( "classes" );
```
Comment (lucamolteni) [inline drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/NativeJavaCompiler.java:392]: Does this work in Java11/Native image?

**Review by lucamolteni — CHANGES_REQUESTED** [review]

**Comment by tkobayas** [comment]
kie-dmn-validation failed to build on my end. (openjdk version "11.0.8" 2020-07-14 LTS)
```
[INFO] --- exec-maven-plugin:1.5.0:java (validation-bootstrap) @ kie-dmn-validation ---
...
java.lang.reflect.InvocationTargetException
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:294)
    at java.lang.Thread.run (Thread.java:834)
Caused by: java.lang.ExceptionInInitializerError
    at org.drools.mvel.MVELConstraintBuilder.createJavaDialectConfiguration (MVELConstraintBuilder.java:132)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.buildDialectConfigurationMap (KnowledgeBuilderConfigurationImpl.java:400)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.init (KnowledgeBuilderConfigurationImpl.java:243)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.init (KnowledgeBuilderConfigurationImpl.java:197)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.<init> (KnowledgeBuilderConfigurationImpl.java:165)
    at org.drools.compiler.kie.builder.impl.KieBuilderImpl.compileJavaClasses (KieBuilderImpl.java:717)
    at org.drools.compiler.kie.builder.impl.KieBuilderImpl.buildAll (KieBuilderImpl.java:244)
    at org.kie.dmn.validation.bootstrap.GenerateModel.generate (GenerateModel.java:64)
    at org.kie.dmn.validation.bootstrap.ValidationBootstrapMain.main (ValidationBootstrapMain.java:49)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:294)
    at java.lang.Thread.run (Thread.java:834)
Caused by: java.lang.RuntimeException: value '11.0.8' is not a valid language level
    at org.drools.compiler.compiler.JavaConfiguration.setJavaLanguageLevel (JavaConfiguration.java:156)
    at org.drools.compiler.compiler.JavaConfiguration.init (JavaConfiguration.java:131)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.buildDialectConfigurationMap (KnowledgeBuilderConfigurationImpl.java:401)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.init (KnowledgeBuilderConfigurationImpl.java:243)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.init (KnowledgeBuilderConfigurationImpl.java:197)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.<init> (KnowledgeBuilderConfigurationImpl.java:165)
    at org.drools.compiler.compiler.JavaConfiguration.<clinit> (JavaConfiguration.java:85)
    at org.drools.mvel.MVELConstraintBuilder.createJavaDialectConfiguration (MVELConstraintBuilder.java:132)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.buildDialectConfigurationMap (KnowledgeBuilderConfigurationImpl.java:400)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.init (KnowledgeBuilderConfigurationImpl.java:243)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.init (KnowledgeBuilderConfigurationImpl.java:197)
    at org.drools.compiler.builder.impl.KnowledgeBuilderConfigurationImpl.<init> (KnowledgeBuilderConfigurationImpl.java:165)
    at org.drools.compiler.kie.builder.impl.KieBuilderImpl.compileJavaClasses (KieBuilderImpl.java:717)
    at org.drools.compiler.kie.builder.impl.KieBuilderImpl.buildAll (KieBuilderImpl.java:244)
    at org.kie.dmn.validation.bootstrap.GenerateModel.generate (GenerateModel.java:64)
    at org.kie.dmn.validation.bootstrap.ValidationBootstrapMain.main (ValidationBootstrapMain.java:49)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:294)
    at java.lang.Thread.run (Thread.java:834)
```

File: drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/NativeJavaCompiler.java (hunk 1 above)
Comment (mariofusco) [reply drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/NativeJavaCompiler.java:392]: This happens only at compile time, so I believe there shouldn't be any problem with the native image.

File: drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/JavaCompilerFactory.java [hunk 2]
```diff
@@ -70,7 +52,7 @@ public JavaCompiler createCompiler(final String pHint) {
         }
         
         try {
-            return (JavaCompiler) clazz.newInstance();
+            return (JavaCompiler) clazz.getConstructor().newInstance();
         } catch (Throwable t) {
             return null;
```
Comment (danielezonca) [inline drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/JavaCompilerFactory.java]: It is a bit unrelated but why don't return `Optional<JavaCompiler>` if it can silently fail?

File: drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/JavaCompilerFactory.java [hunk 3]
```diff
@@ -81,34 +63,20 @@ public JavaCompiler loadCompiler( JavaConfiguration configuration) {
     }
 
     public JavaCompiler loadCompiler( JavaConfiguration.CompilerType compilerType, String lngLevel ) {
```
Comment (danielezonca) [inline drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/JavaCompilerFactory.java]: What is the differences between `loadCompiler` and `createCompiler`? Both create it so it seems to be just an overload

File: drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/JavaCompilerFactory.java [hunk 4]
```diff
@@ -81,34 +63,20 @@ public JavaCompiler loadCompiler( JavaConfiguration configuration) {
...
+        } else {
+            compiler.setJavaCompilerSettings( updateSettings( compiler.createDefaultSettings(), lngLevel ) );
         }
         return compiler;
     }
 
     private JavaCompilerSettings updateSettings( JavaCompilerSettings settings, String lngLevel ) {
         settings.setTargetVersion( lngLevel );
-        settings.setSourceVersion( lngLevel );
+        if (lngLevel.startsWith( "1." )) { // avoid in memory compilation with JPMS
```
Comment (danielezonca) [inline drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/JavaCompilerFactory.java]: Why this hack?

File: drools-ecj/pom.xml [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
+    <parent>
+        <artifactId>drools</artifactId>
+        <groupId>org.drools</groupId>
+        <version>7.47.0-SNAPSHOT</version>
+    </parent>
+    <modelVersion>4.0.0</modelVersion>
+
+    <name>Drools :: ECJ</name>
```
Comment (danielezonca) [inline drools-ecj/pom.xml:26]: Do you think it makes sense to keep the shading of ecj in this pom? The original problem was to avoid clashing with GWT ecj version and this could still happen. Now with the descoping I think the shading should be preserved: if you want to avoid ECJ you can while if you explicitly add this dependency having it shaded or not should be the same. Wdyt?

Comment (danielezonca) [inline drools-ecj/pom.xml:26]: What about `drools-engine-classic`? Do we want to keep ecj in that "bundle"? As default?

Comment (danielezonca) [inline drools-ecj/pom.xml:26]: I'm worried that now we will not test ecj anymore at all because it is not the default and it is not explicitly declared/used anywhere as far as I can see.
Do you think it make sense to add ecj tests as parametrized junit? only some tests? the whole test suite?
I'm not sure we want to deprecate ecj or we just want to make it optional but we want to be sure everything still works
We can improve with other tickets, now I would like to understand the direction

File: drools-compiler/src/main/java/org/drools/compiler/compiler/JavaConfiguration.java [hunk 6]
```diff
@@ -192,11 +195,10 @@ public CompilerType getCompiler() {
      */
     private CompilerType getDefaultCompiler() {
         try {
-            final String prop = this.conf.getChainedProperties().getProperty( JAVA_COMPILER_PROPERTY,
-                                                                              "ECLIPSE" );
-            if ( prop.equals( "NATIVE" ) ) {
+            final String prop = this.conf.getChainedProperties().getProperty( JAVA_COMPILER_PROPERTY, hasEclipseCompiler() ? "ECLIPSE" : "NATIVE" );
```
Comment (danielezonca) [inline drools-compiler/src/main/java/org/drools/compiler/compiler/JavaConfiguration.java:214]: We should document this behavior, personally I don't like a "dynamic" default based on classpath.
Is it for backward compatibility?
In any case, can you please add a `log.debug` with the selected value to make it easier to debug?
Something like
```java
log.debug("Selected compiler " + prop + " [drools.dialect.java.compiler:" + this.conf.getChainedProperties().getProperty( JAVA_COMPILER_PROPERTY, null) + ", hasEclipseCompiler:" + hasEclipseCompiler() + "]");
```

File: drools-compiler/src/main/java/org/drools/compiler/compiler/JavaConfiguration.java [hunk 7]
```diff
@@ -77,25 +79,48 @@
...
+        public String getImplClassName() {
+            return implClassName;
+        }
     }
 
-    // This should be in alphabetic order to search with BinarySearch
-    protected static final String[]  LANGUAGE_LEVELS = new String[]{"1.5", "1.6", "1.7", "1.8", "10", "11", "12", "9"};
+    public static JavaCompiler createDefaultCompiler() {
+        JavaCompiler javaCompiler = JavaCompilerFactory.INSTANCE.loadCompiler(DEFAULT_JAVA_CONFIGURATION.getCompiler(), DEFAULT_JAVA_VERSION);
+        javaCompiler.setSourceFolder("src/main/java/");
```
Comment (danielezonca) [inline drools-compiler/src/main/java/org/drools/compiler/compiler/JavaConfiguration.java]: Is it possible to move this configuration as part of `DEFAULT_JAVA_CONFIGURATION`?

File: drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/NativeJavaCompiler.java [hunk 8]
```diff
@@ -347,12 +357,52 @@ public boolean hasLocation(Location location) {
...
                     }
                 }
-                return result == null ? Collections.<JavaFileObject>emptyList() : result;
+                return result == null ? Collections.emptyList() : result;
             } catch (IOException e) {
                 return Collections.emptyList();
             }
         }
 
+        private List<JavaFileObject> findClassesIndexed(String packageName) {
```
Comment (danielezonca) [inline drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/NativeJavaCompiler.java]: What do you mean with "Indexed"?

File: drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/JavaCompilerFactory.java (hunk 3 above)
Comment (mariofusco) [reply drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/JavaCompilerFactory.java]: `createCompiler` is just an internal impl, I made it private.

File: drools-compiler/src/main/java/org/drools/compiler/compiler/JavaConfiguration.java (hunk 6 above)
Comment (mariofusco) [reply drools-compiler/src/main/java/org/drools/compiler/compiler/JavaConfiguration.java:214]: The idea is that if you brought ecj in your classpath it is because you want to use it and then it makes it the default choice without the need of any further settings. I understand this behaviour is questionable and I'm open to discuss it.

File: drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/JavaCompilerFactory.java (hunk 4 above)
Comment (mariofusco) [reply drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/JavaCompilerFactory.java]: This is to force the native java compiler to work with a 1.8 source level (or less). If I make it run with 9+ (i.e. with JPMS) I get weird compilation errors like the following
`UNKNOWN (-1:-1) : module jdk.accessibility reads package  from both java.base and java.naming`
I spent quite a lot of time trying to figure out what's going on here but I'm clueless so far. I understand that this a ugly hack and something that I should fix asap. Also it is quite surprising that ecj seems not suffer of the same problem, but still I haven't been able yet to figure out why.

File: drools-ecj/pom.xml (hunk 5 above)
Comment (mariofusco) [reply drools-ecj/pom.xml:26]: I was hoping that making ecj optional would also make that shading no longer useful, which is also one of the main reason for this descoping, see also what's reported in original ticket https://issues.redhat.com/browse/DROOLS-5780
In essence the best way to overcome the problem is not using ecj at all, but yes, I agree that if a user brings the` drools-ecj` module in and wants to use it with GWT we should do the shading anyway. Let's discuss this.

**Comment by danielezonca** [comment]
jenkins retest this please

File: drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/JavaCompilerFactory.java (hunk 4 above)
Comment (danielezonca) [reply drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/JavaCompilerFactory.java]: Does it mean that user will not be able to use >1.8 code in DRL until this is fixed?

File: drools-ecj/pom.xml (hunk 5 above)
Comment (mariofusco) [reply drools-ecj/pom.xml:26]: I will add a profile to test ecj.

File: drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/JavaCompilerFactory.java (hunk 4 above)
Comment (mariofusco) [reply drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/JavaCompilerFactory.java]: For now yes, I will avoid this for ecj.

File: drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/NativeJavaCompiler.java (hunk 8 above)
Comment (danielezonca) [reply drools-compiler/src/main/java/org/drools/compiler/commons/jci/compilers/NativeJavaCompiler.java]: What about `findClassesFromPackage`?

**Review by danielezonca — APPROVED** [review]
Thanks for the PR, approving :+1:

**Comment by mariofusco** [comment]
jenkins execute fdb

**Review by tkobayas — APPROVED** [review]

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins retest this

**Comment by mariofusco** [comment]
jenkins retest this

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by mariofusco** [comment]
The 2 failures

```
org.uberfire.java.nio.fs.file.SimpleUnixFileStoreTest.simpleTests

Error Message

expected:<81739[49747]2L> but was:<81739[68179]2L>

Stacktrace

org.junit.ComparisonFailure: expected:<81739[49747]2L> but was:<81739[68179]2L>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```

and

```
org.kie.workbench.common.services.backend.builder.core.BuilderTest.testBuilderFixForBrokenKModule

Stacktrace

java.lang.NullPointerException
	at org.kie.workbench.common.services.backend.builder.core.ClassVerifier.verify(ClassVerifier.java:52)
	at org.kie.workbench.common.services.backend.builder.core.Builder.verifyClasses(Builder.java:292)
```

are clearly unrelated.
