### PR TITLE
[DROOLS-6622] Bump Mvel version to 2.4.13

### PR DESCRIPTION
**Pull request by tkobayas**
**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6622

**referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1781

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by tkobayas** [comment]
Jenkins retest this

File: drools-mvel/src/test/java/org/drools/mvel/compiler/rule/builder/dialect/mvel/MVELDebugTest.java [hunk 1]
```diff
@@ -40,11 +39,9 @@ public void testDebug() throws Exception {
         builder.addPackage(packageDescr);
         InternalKnowledgePackage pkg = builder.getPackage("com.sample");
         MVELConsequence consequence = (MVELConsequence) pkg.getRule("myRule").getConsequence();
-        String sourceName = ((CompiledExpression) consequence.getCompExpr()).getSourceName();
```
Comment (tkobayas) [inline drools-mvel/src/test/java/org/drools/mvel/compiler/rule/builder/dialect/mvel/MVELDebugTest.java:43]: Hi @mariofusco 

When I bumped mvel to 2.4.13.Final, I hit a compilation error in drools-mvel's MVELDebugTest.java.
```
2021-09-28T05:22:52.2529652Z Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
2021-09-28T05:22:52.2531720Z /home/runner/work/drools/drools/kiegroup_drools/drools-mvel/src/test/java/org/drools/mvel/compiler/rule/builder/dialect/mvel/MVELDebugTest.java:[43,77] cannot find symbol
2021-09-28T05:22:52.2532695Z   symbol:   method getSourceName()
2021-09-28T05:22:52.2533466Z   location: class org.mvel2.compiler.CompiledExpression
```

method `getSourceName` was removed from `CompiledExpression` with this commit.

https://github.com/mvel/mvel/commit/dac8d0318c2e617cf65fc5d91f81208fc300f4f3

Is this intentional?

Other drools tests seem to work. 

(Anyway, Jenkins is not working so we should not merge now. When Jenkins is back, I'll run FDB)

**Comment by tkobayas** [comment]
Jenkins retest this

**Comment by tkobayas** [comment]
Jenkins run fdb

**Comment by tkobayas** [comment]
FDB was tested by https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1781

File: drools-mvel/src/test/java/org/drools/mvel/compiler/rule/builder/dialect/mvel/MVELDebugTest.java (hunk 1 above)
Comment (tkobayas) [reply drools-mvel/src/test/java/org/drools/mvel/compiler/rule/builder/dialect/mvel/MVELDebugTest.java:43]: Confirmed with Mario. It's okay.

**Comment by tkobayas** [comment]
Firstly, I'll raise a PR against 7.x with the same name branch `DROOLS-6622` (https://github.com/kiegroup/drools/pull/3867) because it should be tested with https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1781 . So closing this PR for now. Then, I'll raise a forward port PR to main.

**Comment by tkobayas** [comment]
for main, I filed
https://github.com/kiegroup/droolsjbpm-knowledge/pull/562
https://github.com/kiegroup/drools/pull/3871
